# PR_COMMENT_EVENT = '''{
#   "action": "created",
#   "comment": {
#     "url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/comments/29724692",
#     "id": 29724692,
#     "diff_hunk": "@@ -1 +1 @@-# public-repo",
#     "path": "README.md",
#     "position": 1,
#     "original_position": 1,
#     "commit_id": "0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c",
#     "original_commit_id": "0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c",
#     "user": {
#       "login": "baxterthehacker",
#       "id": 6752317,
#       "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#       "gravatar_id": "",
#       "url": "https://api.github.com/users/baxterthehacker",
#       "html_url": "https://github.com/baxterthehacker",
#       "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#       "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#       "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#       "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#       "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#       "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#       "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#       "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#       "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#       "type": "User",
#       "site_admin": false
#     },
#     "body": "COMMENT_BODY",
#     "created_at": "2015-05-05T23:40:27Z",
#     "updated_at": "2015-05-05T23:40:27Z",
#     "html_url": "https://github.com/baxterthehacker/public-repo/pull/1#discussion_r29724692",
#     "pull_request_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1",
#     "_links": {
#       "self": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/comments/29724692"
#       },
#       "html": {
#         "href": "https://github.com/baxterthehacker/public-repo/pull/1#discussion_r29724692"
#       },
#       "pull_request": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1"
#       }
#     }
#   },
#   "pull_request": {
#     "url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1",
#     "id": 34778301,
#     "html_url": "https://github.com/baxterthehacker/public-repo/pull/1",
#     "diff_url": "https://github.com/baxterthehacker/public-repo/pull/1.diff",
#     "patch_url": "https://github.com/baxterthehacker/public-repo/pull/1.patch",
#     "issue_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/1",
#     "number": 1,
#     "state": "open",
#     "locked": false,
#     "title": "Update the README with new information",
#     "user": {
#       "login": "baxterthehacker",
#       "id": 6752317,
#       "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#       "gravatar_id": "",
#       "url": "https://api.github.com/users/baxterthehacker",
#       "html_url": "https://github.com/baxterthehacker",
#       "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#       "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#       "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#       "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#       "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#       "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#       "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#       "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#       "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#       "type": "User",
#       "site_admin": false
#     },
#     "body": "This is a pretty simple change that we need to pull into master.",
#     "created_at": "2015-05-05T23:40:27Z",
#     "updated_at": "2015-05-05T23:40:27Z",
#     "closed_at": null,
#     "merged_at": null,
#     "merge_commit_sha": "18721552ba489fb84e12958c1b5694b5475f7991",
#     "assignee": null,
#     "milestone": null,
#     "commits_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1/commits",
#     "review_comments_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1/comments",
#     "review_comment_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/comments{/number}",
#     "comments_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/1/comments",
#     "statuses_url": "https://api.github.com/repos/baxterthehacker/public-repo/statuses/0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c",
#     "head": {
#       "label": "baxterthehacker:changes",
#       "ref": "changes",
#       "sha": "0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c",
#       "user": {
#         "login": "baxterthehacker",
#         "id": 6752317,
#         "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#         "gravatar_id": "",
#         "url": "https://api.github.com/users/baxterthehacker",
#         "html_url": "https://github.com/baxterthehacker",
#         "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#         "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#         "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#         "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#         "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#         "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#         "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#         "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#         "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#         "type": "User",
#         "site_admin": false
#       },
#       "repo": {
#         "id": 35129377,
#         "name": "public-repo",
#         "full_name": "baxterthehacker/public-repo",
#         "owner": {
#           "login": "baxterthehacker",
#           "id": 6752317,
#           "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#           "gravatar_id": "",
#           "url": "https://api.github.com/users/baxterthehacker",
#           "html_url": "https://github.com/baxterthehacker",
#           "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#           "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#           "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#           "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#           "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#           "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#           "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#           "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#           "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#           "type": "User",
#           "site_admin": false
#         },
#         "private": false,
#         "html_url": "https://github.com/baxterthehacker/public-repo",
#         "description": "",
#         "fork": false,
#         "url": "https://api.github.com/repos/baxterthehacker/public-repo",
#         "forks_url": "https://api.github.com/repos/baxterthehacker/public-repo/forks",
#         "keys_url": "https://api.github.com/repos/baxterthehacker/public-repo/keys{/key_id}",
#         "collaborators_url": "https://api.github.com/repos/baxterthehacker/public-repo/collaborators{/collaborator}",
#         "teams_url": "https://api.github.com/repos/baxterthehacker/public-repo/teams",
#         "hooks_url": "https://api.github.com/repos/baxterthehacker/public-repo/hooks",
#         "issue_events_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/events{/number}",
#         "events_url": "https://api.github.com/repos/baxterthehacker/public-repo/events",
#         "assignees_url": "https://api.github.com/repos/baxterthehacker/public-repo/assignees{/user}",
#         "branches_url": "https://api.github.com/repos/baxterthehacker/public-repo/branches{/branch}",
#         "tags_url": "https://api.github.com/repos/baxterthehacker/public-repo/tags",
#         "blobs_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/blobs{/sha}",
#         "git_tags_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/tags{/sha}",
#         "git_refs_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/refs{/sha}",
#         "trees_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/trees{/sha}",
#         "statuses_url": "https://api.github.com/repos/baxterthehacker/public-repo/statuses/{sha}",
#         "languages_url": "https://api.github.com/repos/baxterthehacker/public-repo/languages",
#         "stargazers_url": "https://api.github.com/repos/baxterthehacker/public-repo/stargazers",
#         "contributors_url": "https://api.github.com/repos/baxterthehacker/public-repo/contributors",
#         "subscribers_url": "https://api.github.com/repos/baxterthehacker/public-repo/subscribers",
#         "subscription_url": "https://api.github.com/repos/baxterthehacker/public-repo/subscription",
#         "commits_url": "https://api.github.com/repos/baxterthehacker/public-repo/commits{/sha}",
#         "git_commits_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/commits{/sha}",
#         "comments_url": "https://api.github.com/repos/baxterthehacker/public-repo/comments{/number}",
#         "issue_comment_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/comments{/number}",
#         "contents_url": "https://api.github.com/repos/baxterthehacker/public-repo/contents/{+path}",
#         "compare_url": "https://api.github.com/repos/baxterthehacker/public-repo/compare/{base}...{head}",
#         "merges_url": "https://api.github.com/repos/baxterthehacker/public-repo/merges",
#         "archive_url": "https://api.github.com/repos/baxterthehacker/public-repo/{archive_format}{/ref}",
#         "downloads_url": "https://api.github.com/repos/baxterthehacker/public-repo/downloads",
#         "issues_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues{/number}",
#         "pulls_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls{/number}",
#         "milestones_url": "https://api.github.com/repos/baxterthehacker/public-repo/milestones{/number}",
#         "notifications_url": "https://api.github.com/repos/baxterthehacker/public-repo/notifications{?since,all,participating}",
#         "labels_url": "https://api.github.com/repos/baxterthehacker/public-repo/labels{/name}",
#         "releases_url": "https://api.github.com/repos/baxterthehacker/public-repo/releases{/id}",
#         "created_at": "2015-05-05T23:40:12Z",
#         "updated_at": "2015-05-05T23:40:12Z",
#         "pushed_at": "2015-05-05T23:40:27Z",
#         "git_url": "git://github.com/baxterthehacker/public-repo.git",
#         "ssh_url": "git@github.com:baxterthehacker/public-repo.git",
#         "clone_url": "https://github.com/baxterthehacker/public-repo.git",
#         "svn_url": "https://github.com/baxterthehacker/public-repo",
#         "homepage": null,
#         "size": 0,
#         "stargazers_count": 0,
#         "watchers_count": 0,
#         "language": null,
#         "has_issues": true,
#         "has_downloads": true,
#         "has_wiki": true,
#         "has_pages": true,
#         "forks_count": 0,
#         "mirror_url": null,
#         "open_issues_count": 1,
#         "forks": 0,
#         "open_issues": 1,
#         "watchers": 0,
#         "default_branch": "master"
#       }
#     },
#     "base": {
#       "label": "baxterthehacker:master",
#       "ref": "master",
#       "sha": "9049f1265b7d61be4a8904a9a27120d2064dab3b",
#       "user": {
#         "login": "baxterthehacker",
#         "id": 6752317,
#         "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#         "gravatar_id": "",
#         "url": "https://api.github.com/users/baxterthehacker",
#         "html_url": "https://github.com/baxterthehacker",
#         "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#         "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#         "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#         "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#         "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#         "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#         "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#         "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#         "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#         "type": "User",
#         "site_admin": false
#       },
#       "repo": {
#         "id": 35129377,
#         "name": "public-repo",
#         "full_name": "baxterthehacker/public-repo",
#         "owner": {
#           "login": "baxterthehacker",
#           "id": 6752317,
#           "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#           "gravatar_id": "",
#           "url": "https://api.github.com/users/baxterthehacker",
#           "html_url": "https://github.com/baxterthehacker",
#           "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#           "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#           "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#           "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#           "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#           "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#           "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#           "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#           "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#           "type": "User",
#           "site_admin": false
#         },
#         "private": false,
#         "html_url": "https://github.com/baxterthehacker/public-repo",
#         "description": "",
#         "fork": false,
#         "url": "https://api.github.com/repos/baxterthehacker/public-repo",
#         "forks_url": "https://api.github.com/repos/baxterthehacker/public-repo/forks",
#         "keys_url": "https://api.github.com/repos/baxterthehacker/public-repo/keys{/key_id}",
#         "collaborators_url": "https://api.github.com/repos/baxterthehacker/public-repo/collaborators{/collaborator}",
#         "teams_url": "https://api.github.com/repos/baxterthehacker/public-repo/teams",
#         "hooks_url": "https://api.github.com/repos/baxterthehacker/public-repo/hooks",
#         "issue_events_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/events{/number}",
#         "events_url": "https://api.github.com/repos/baxterthehacker/public-repo/events",
#         "assignees_url": "https://api.github.com/repos/baxterthehacker/public-repo/assignees{/user}",
#         "branches_url": "https://api.github.com/repos/baxterthehacker/public-repo/branches{/branch}",
#         "tags_url": "https://api.github.com/repos/baxterthehacker/public-repo/tags",
#         "blobs_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/blobs{/sha}",
#         "git_tags_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/tags{/sha}",
#         "git_refs_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/refs{/sha}",
#         "trees_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/trees{/sha}",
#         "statuses_url": "https://api.github.com/repos/baxterthehacker/public-repo/statuses/{sha}",
#         "languages_url": "https://api.github.com/repos/baxterthehacker/public-repo/languages",
#         "stargazers_url": "https://api.github.com/repos/baxterthehacker/public-repo/stargazers",
#         "contributors_url": "https://api.github.com/repos/baxterthehacker/public-repo/contributors",
#         "subscribers_url": "https://api.github.com/repos/baxterthehacker/public-repo/subscribers",
#         "subscription_url": "https://api.github.com/repos/baxterthehacker/public-repo/subscription",
#         "commits_url": "https://api.github.com/repos/baxterthehacker/public-repo/commits{/sha}",
#         "git_commits_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/commits{/sha}",
#         "comments_url": "https://api.github.com/repos/baxterthehacker/public-repo/comments{/number}",
#         "issue_comment_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/comments{/number}",
#         "contents_url": "https://api.github.com/repos/baxterthehacker/public-repo/contents/{+path}",
#         "compare_url": "https://api.github.com/repos/baxterthehacker/public-repo/compare/{base}...{head}",
#         "merges_url": "https://api.github.com/repos/baxterthehacker/public-repo/merges",
#         "archive_url": "https://api.github.com/repos/baxterthehacker/public-repo/{archive_format}{/ref}",
#         "downloads_url": "https://api.github.com/repos/baxterthehacker/public-repo/downloads",
#         "issues_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues{/number}",
#         "pulls_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls{/number}",
#         "milestones_url": "https://api.github.com/repos/baxterthehacker/public-repo/milestones{/number}",
#         "notifications_url": "https://api.github.com/repos/baxterthehacker/public-repo/notifications{?since,all,participating}",
#         "labels_url": "https://api.github.com/repos/baxterthehacker/public-repo/labels{/name}",
#         "releases_url": "https://api.github.com/repos/baxterthehacker/public-repo/releases{/id}",
#         "created_at": "2015-05-05T23:40:12Z",
#         "updated_at": "2015-05-05T23:40:12Z",
#         "pushed_at": "2015-05-05T23:40:27Z",
#         "git_url": "git://github.com/baxterthehacker/public-repo.git",
#         "ssh_url": "git@github.com:baxterthehacker/public-repo.git",
#         "clone_url": "https://github.com/baxterthehacker/public-repo.git",
#         "svn_url": "https://github.com/baxterthehacker/public-repo",
#         "homepage": null,
#         "size": 0,
#         "stargazers_count": 0,
#         "watchers_count": 0,
#         "language": null,
#         "has_issues": true,
#         "has_downloads": true,
#         "has_wiki": true,
#         "has_pages": true,
#         "forks_count": 0,
#         "mirror_url": null,
#         "open_issues_count": 1,
#         "forks": 0,
#         "open_issues": 1,
#         "watchers": 0,
#         "default_branch": "master"
#       }
#     },
#     "_links": {
#       "self": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1"
#       },
#       "html": {
#         "href": "https://github.com/baxterthehacker/public-repo/pull/1"
#       },
#       "issue": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/issues/1"
#       },
#       "comments": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/issues/1/comments"
#       },
#       "review_comments": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1/comments"
#       },
#       "review_comment": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/comments{/number}"
#       },
#       "commits": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/pulls/1/commits"
#       },
#       "statuses": {
#         "href": "https://api.github.com/repos/baxterthehacker/public-repo/statuses/0d1a26e67d8f5eaf1f6ba5c57fc3c7d91ac0fd1c"
#       }
#     }
#   },
#   "repository": {
#     "id": 35129377,
#     "name": "public-repo",
#     "full_name": "baxterthehacker/public-repo",
#     "owner": {
#       "login": "baxterthehacker",
#       "id": 6752317,
#       "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#       "gravatar_id": "",
#       "url": "https://api.github.com/users/baxterthehacker",
#       "html_url": "https://github.com/baxterthehacker",
#       "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#       "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#       "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#       "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#       "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#       "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#       "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#       "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#       "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#       "type": "User",
#       "site_admin": false
#     },
#     "private": false,
#     "html_url": "https://github.com/baxterthehacker/public-repo",
#     "description": "",
#     "fork": false,
#     "url": "https://api.github.com/repos/baxterthehacker/public-repo",
#     "forks_url": "https://api.github.com/repos/baxterthehacker/public-repo/forks",
#     "keys_url": "https://api.github.com/repos/baxterthehacker/public-repo/keys{/key_id}",
#     "collaborators_url": "https://api.github.com/repos/baxterthehacker/public-repo/collaborators{/collaborator}",
#     "teams_url": "https://api.github.com/repos/baxterthehacker/public-repo/teams",
#     "hooks_url": "https://api.github.com/repos/baxterthehacker/public-repo/hooks",
#     "issue_events_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/events{/number}",
#     "events_url": "https://api.github.com/repos/baxterthehacker/public-repo/events",
#     "assignees_url": "https://api.github.com/repos/baxterthehacker/public-repo/assignees{/user}",
#     "branches_url": "https://api.github.com/repos/baxterthehacker/public-repo/branches{/branch}",
#     "tags_url": "https://api.github.com/repos/baxterthehacker/public-repo/tags",
#     "blobs_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/blobs{/sha}",
#     "git_tags_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/tags{/sha}",
#     "git_refs_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/refs{/sha}",
#     "trees_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/trees{/sha}",
#     "statuses_url": "https://api.github.com/repos/baxterthehacker/public-repo/statuses/{sha}",
#     "languages_url": "https://api.github.com/repos/baxterthehacker/public-repo/languages",
#     "stargazers_url": "https://api.github.com/repos/baxterthehacker/public-repo/stargazers",
#     "contributors_url": "https://api.github.com/repos/baxterthehacker/public-repo/contributors",
#     "subscribers_url": "https://api.github.com/repos/baxterthehacker/public-repo/subscribers",
#     "subscription_url": "https://api.github.com/repos/baxterthehacker/public-repo/subscription",
#     "commits_url": "https://api.github.com/repos/baxterthehacker/public-repo/commits{/sha}",
#     "git_commits_url": "https://api.github.com/repos/baxterthehacker/public-repo/git/commits{/sha}",
#     "comments_url": "https://api.github.com/repos/baxterthehacker/public-repo/comments{/number}",
#     "issue_comment_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues/comments{/number}",
#     "contents_url": "https://api.github.com/repos/baxterthehacker/public-repo/contents/{+path}",
#     "compare_url": "https://api.github.com/repos/baxterthehacker/public-repo/compare/{base}...{head}",
#     "merges_url": "https://api.github.com/repos/baxterthehacker/public-repo/merges",
#     "archive_url": "https://api.github.com/repos/baxterthehacker/public-repo/{archive_format}{/ref}",
#     "downloads_url": "https://api.github.com/repos/baxterthehacker/public-repo/downloads",
#     "issues_url": "https://api.github.com/repos/baxterthehacker/public-repo/issues{/number}",
#     "pulls_url": "https://api.github.com/repos/baxterthehacker/public-repo/pulls{/number}",
#     "milestones_url": "https://api.github.com/repos/baxterthehacker/public-repo/milestones{/number}",
#     "notifications_url": "https://api.github.com/repos/baxterthehacker/public-repo/notifications{?since,all,participating}",
#     "labels_url": "https://api.github.com/repos/baxterthehacker/public-repo/labels{/name}",
#     "releases_url": "https://api.github.com/repos/baxterthehacker/public-repo/releases{/id}",
#     "created_at": "2015-05-05T23:40:12Z",
#     "updated_at": "2015-05-05T23:40:12Z",
#     "pushed_at": "2015-05-05T23:40:27Z",
#     "git_url": "git://github.com/baxterthehacker/public-repo.git",
#     "ssh_url": "git@github.com:baxterthehacker/public-repo.git",
#     "clone_url": "https://github.com/baxterthehacker/public-repo.git",
#     "svn_url": "https://github.com/baxterthehacker/public-repo",
#     "homepage": null,
#     "size": 0,
#     "stargazers_count": 0,
#     "watchers_count": 0,
#     "language": null,
#     "has_issues": true,
#     "has_downloads": true,
#     "has_wiki": true,
#     "has_pages": true,
#     "forks_count": 0,
#     "mirror_url": null,
#     "open_issues_count": 1,
#     "forks": 0,
#     "open_issues": 1,
#     "watchers": 0,
#     "default_branch": "master"
#   },
#   "sender": {
#     "login": "baxterthehacker",
#     "id": 6752317,
#     "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
#     "gravatar_id": "",
#     "url": "https://api.github.com/users/baxterthehacker",
#     "html_url": "https://github.com/baxterthehacker",
#     "followers_url": "https://api.github.com/users/baxterthehacker/followers",
#     "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
#     "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
#     "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
#     "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
#     "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
#     "repos_url": "https://api.github.com/users/baxterthehacker/repos",
#     "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
#     "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
#     "type": "User",
#     "site_admin": false
#   }
# }'''

ISSUE_RESPONSE_OPEN = '''
{
  "id": 1,
  "url": "https://api.github.com/repos/octocat/Hello-World/issues/1347",
  "repository_url": "https://api.github.com/repos/octocat/Hello-World",
  "labels_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/labels{/name}",
  "comments_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/comments",
  "events_url": "https://api.github.com/repos/octocat/Hello-World/issues/1347/events",
  "html_url": "https://github.com/octocat/Hello-World/issues/1347",
  "number": 1347,
  "state": "open",
  "title": "Found a bug",
  "body": "I'm having a problem with this.",
  "user": {
    "login": "octocat",
    "id": 1,
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 208045946,
      "url": "https://api.github.com/repos/octocat/Hello-World/labels/bug",
      "name": "bug",
      "color": "f29513",
      "default": true
    }
  ],
  "assignee": {
    "login": "octocat",
    "id": 1,
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false
  },
  "assignees": [
    {
      "login": "octocat",
      "id": 1,
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    }
  ],
  "milestone": {
    "url": "https://api.github.com/repos/octocat/Hello-World/milestones/1",
    "html_url": "https://github.com/octocat/Hello-World/milestones/v1.0",
    "labels_url": "https://api.github.com/repos/octocat/Hello-World/milestones/1/labels",
    "id": 1002604,
    "number": 1,
    "state": "open",
    "title": "v1.0",
    "description": "Tracking milestone for version 1.0",
    "creator": {
      "login": "octocat",
      "id": 1,
      "avatar_url": "https://github.com/images/error/octocat_happy.gif",
      "gravatar_id": "",
      "url": "https://api.github.com/users/octocat",
      "html_url": "https://github.com/octocat",
      "followers_url": "https://api.github.com/users/octocat/followers",
      "following_url": "https://api.github.com/users/octocat/following{/other_user}",
      "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
      "organizations_url": "https://api.github.com/users/octocat/orgs",
      "repos_url": "https://api.github.com/users/octocat/repos",
      "events_url": "https://api.github.com/users/octocat/events{/privacy}",
      "received_events_url": "https://api.github.com/users/octocat/received_events",
      "type": "User",
      "site_admin": false
    },
    "open_issues": 4,
    "closed_issues": 8,
    "created_at": "2011-04-10T20:09:31Z",
    "updated_at": "2014-03-03T18:58:10Z",
    "closed_at": "2013-02-12T13:22:01Z",
    "due_on": "2012-10-09T23:39:01Z"
  },
  "locked": true,
  "active_lock_reason": "too heated",
  "comments": 0,
  "pull_request": {
    "url": "https://api.github.com/repos/octocat/Hello-World/pulls/1347",
    "html_url": "https://github.com/octocat/Hello-World/pull/1347",
    "diff_url": "https://github.com/octocat/Hello-World/pull/1347.diff",
    "patch_url": "https://github.com/octocat/Hello-World/pull/1347.patch"
  },
  "closed_at": null,
  "created_at": "2011-04-22T13:33:48Z",
  "updated_at": "2011-04-22T13:33:48Z",
  "closed_by": {
    "login": "octocat",
    "id": 1,
    "avatar_url": "https://github.com/images/error/octocat_happy.gif",
    "gravatar_id": "",
    "url": "https://api.github.com/users/octocat",
    "html_url": "https://github.com/octocat",
    "followers_url": "https://api.github.com/users/octocat/followers",
    "following_url": "https://api.github.com/users/octocat/following{/other_user}",
    "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
    "organizations_url": "https://api.github.com/users/octocat/orgs",
    "repos_url": "https://api.github.com/users/octocat/repos",
    "events_url": "https://api.github.com/users/octocat/events{/privacy}",
    "received_events_url": "https://api.github.com/users/octocat/received_events",
    "type": "User",
    "site_admin": false
  }
}'''

PR_COMMENT_EVENT = """
    {'action': 'created',
    'issue': {'url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/11',
              'repository_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck',
              'labels_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/11/labels{/name}',
              'comments_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/11/comments',
              'events_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/11/events',
              'html_url': 'https://github.com/alvarocavalcanti/pierre-decheck/pull/11', 'id': 293658982,
              'number': 11, 'title': 'Dummy-two', 'user': {'login': 'alvarocavalcanti', 'id': 512234,
                                                           'avatar_url': 'https://avatars2.githubusercontent.com/u/512234?v=4',
                                                           'gravatar_id': '',
                                                           'url': 'https://api.github.com/users/alvarocavalcanti',
                                                           'html_url': 'https://github.com/alvarocavalcanti',
                                                           'followers_url': 'https://api.github.com/users/alvarocavalcanti/followers',
                                                           'following_url': 'https://api.github.com/users/alvarocavalcanti/following{/other_user}',
                                                           'gists_url': 'https://api.github.com/users/alvarocavalcanti/gists{/gist_id}',
                                                           'starred_url': 'https://api.github.com/users/alvarocavalcanti/starred{/owner}{/repo}',
                                                           'subscriptions_url': 'https://api.github.com/users/alvarocavalcanti/subscriptions',
                                                           'organizations_url': 'https://api.github.com/users/alvarocavalcanti/orgs',
                                                           'repos_url': 'https://api.github.com/users/alvarocavalcanti/repos',
                                                           'events_url': 'https://api.github.com/users/alvarocavalcanti/events{/privacy}',
                                                           'received_events_url': 'https://api.github.com/users/alvarocavalcanti/received_events',
                                                           'type': 'User', 'site_admin': False},
              'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [],
              'milestone': None, 'comments': 1, 'created_at': '2018-02-01T19:43:55Z',
              'updated_at': '2018-02-09T14:49:13Z', 'closed_at': None, 'author_association': 'OWNER',
              'pull_request': {
                  'url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/pulls/11',
                  'html_url': 'https://github.com/alvarocavalcanti/pierre-decheck/pull/11',
                  'diff_url': 'https://github.com/alvarocavalcanti/pierre-decheck/pull/11.diff',
                  'patch_url': 'https://github.com/alvarocavalcanti/pierre-decheck/pull/11.patch'},
              'body': ''},
    'comment': {
        'url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/comments/364454106',
        'html_url': 'https://github.com/alvarocavalcanti/pierre-decheck/pull/11#issuecomment-364454106',
        'issue_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/11', 'id': 364454106,
        'user': {'login': 'alvarocavalcanti', 'id': 512234,
                 'avatar_url': 'https://avatars2.githubusercontent.com/u/512234?v=4', 'gravatar_id': '',
                 'url': 'https://api.github.com/users/alvarocavalcanti',
                 'html_url': 'https://github.com/alvarocavalcanti',
                 'followers_url': 'https://api.github.com/users/alvarocavalcanti/followers',
                 'following_url': 'https://api.github.com/users/alvarocavalcanti/following{/other_user}',
                 'gists_url': 'https://api.github.com/users/alvarocavalcanti/gists{/gist_id}',
                 'starred_url': 'https://api.github.com/users/alvarocavalcanti/starred{/owner}{/repo}',
                 'subscriptions_url': 'https://api.github.com/users/alvarocavalcanti/subscriptions',
                 'organizations_url': 'https://api.github.com/users/alvarocavalcanti/orgs',
                 'repos_url': 'https://api.github.com/users/alvarocavalcanti/repos',
                 'events_url': 'https://api.github.com/users/alvarocavalcanti/events{/privacy}',
                 'received_events_url': 'https://api.github.com/users/alvarocavalcanti/received_events', 'type': 'User',
                 'site_admin': False}, 'created_at': '2018-02-09T14:49:13Z', 'updated_at': '2018-02-09T14:49:13Z',
        'author_association': 'OWNER', 'body': 'depends on #10 '},
                    'repository': {'id': 117260108, 'name': 'pierre-decheck',
                                   'full_name': 'alvarocavalcanti/pierre-decheck',
                                   'owner': {'login': 'alvarocavalcanti', 'id': 512234,
                                             'avatar_url': 'https://avatars2.githubusercontent.com/u/512234?v=4',
                                             'gravatar_id': '', 'url': 'https://api.github.com/users/alvarocavalcanti',
                                             'html_url': 'https://github.com/alvarocavalcanti',
                                             'followers_url': 'https://api.github.com/users/alvarocavalcanti/followers',
                                             'following_url': 'https://api.github.com/users/alvarocavalcanti/following{/other_user}',
                                             'gists_url': 'https://api.github.com/users/alvarocavalcanti/gists{/gist_id}',
                                             'starred_url': 'https://api.github.com/users/alvarocavalcanti/starred{/owner}{/repo}',
                                             'subscriptions_url': 'https://api.github.com/users/alvarocavalcanti/subscriptions',
                                             'organizations_url': 'https://api.github.com/users/alvarocavalcanti/orgs',
                                             'repos_url': 'https://api.github.com/users/alvarocavalcanti/repos',
                                             'events_url': 'https://api.github.com/users/alvarocavalcanti/events{/privacy}',
                                             'received_events_url': 'https://api.github.com/users/alvarocavalcanti/received_events',
                                             'type': 'User', 'site_admin': False}, 'private': False,
                                   'html_url': 'https://github.com/alvarocavalcanti/pierre-decheck',
                                   'description': 'Checks the Dependencies of Pull Requests', 'fork': False,
                                   'url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck',
                                   'forks_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/forks',
                                   'keys_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/keys{/key_id}',
                                   'collaborators_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/collaborators{/collaborator}',
                                   'teams_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/teams',
                                   'hooks_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/hooks',
                                   'issue_events_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/events{/number}',
                                   'events_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/events',
                                   'assignees_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/assignees{/user}',
                                   'branches_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/branches{/branch}',
                                   'tags_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/tags',
                                   'blobs_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/git/blobs{/sha}',
                                   'git_tags_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/git/tags{/sha}',
                                   'git_refs_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/git/refs{/sha}',
                                   'trees_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/git/trees{/sha}',
                                   'statuses_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/statuses/{sha}',
                                   'languages_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/languages',
                                   'stargazers_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/stargazers',
                                   'contributors_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/contributors',
                                   'subscribers_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/subscribers',
                                   'subscription_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/subscription',
                                   'commits_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/commits{/sha}',
                                   'git_commits_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/git/commits{/sha}',
                                   'comments_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/comments{/number}',
                                   'issue_comment_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues/comments{/number}',
                                   'contents_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/contents/{+path}',
                                   'compare_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/compare/{base}...{head}',
                                   'merges_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/merges',
                                   'archive_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/{archive_format}{/ref}',
                                   'downloads_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/downloads',
                                   'issues_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/issues{/number}',
                                   'pulls_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/pulls{/number}',
                                   'milestones_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/milestones{/number}',
                                   'notifications_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/notifications{?since,all,participating}',
                                   'labels_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/labels{/name}',
                                   'releases_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/releases{/id}',
                                   'deployments_url': 'https://api.github.com/repos/alvarocavalcanti/pierre-decheck/deployments',
                                   'created_at': '2018-01-12T15:56:48Z', 'updated_at': '2018-02-01T19:29:20Z',
                                   'pushed_at': '2018-02-09T14:47:47Z',
                                   'git_url': 'git://github.com/alvarocavalcanti/pierre-decheck.git',
                                   'ssh_url': 'git@github.com:alvarocavalcanti/pierre-decheck.git',
                                   'clone_url': 'https://github.com/alvarocavalcanti/pierre-decheck.git',
                                   'svn_url': 'https://github.com/alvarocavalcanti/pierre-decheck', 'homepage': '',
                                   'size': 35, 'stargazers_count': 0, 'watchers_count': 0, 'language': 'Python',
                                   'has_issues': True, 'has_projects': True, 'has_downloads': True, 'has_wiki': True,
                                   'has_pages': False, 'forks_count': 0, 'mirror_url': None, 'archived': False,
                                   'open_issues_count': 9,
                                   'license': {'key': 'mit', 'name': 'MIT License', 'spdx_id': 'MIT',
                                               'url': 'https://api.github.com/licenses/mit'}, 'forks': 0,
                                   'open_issues': 9, 'watchers': 0, 'default_branch': 'master'},
                    'sender': {'login': 'alvarocavalcanti', 'id': 512234,
                               'avatar_url': 'https://avatars2.githubusercontent.com/u/512234?v=4', 'gravatar_id': '',
                               'url': 'https://api.github.com/users/alvarocavalcanti',
                               'html_url': 'https://github.com/alvarocavalcanti',
                               'followers_url': 'https://api.github.com/users/alvarocavalcanti/followers',
                               'following_url': 'https://api.github.com/users/alvarocavalcanti/following{/other_user}',
                               'gists_url': 'https://api.github.com/users/alvarocavalcanti/gists{/gist_id}',
                               'starred_url': 'https://api.github.com/users/alvarocavalcanti/starred{/owner}{/repo}',
                               'subscriptions_url': 'https://api.github.com/users/alvarocavalcanti/subscriptions',
                               'organizations_url': 'https://api.github.com/users/alvarocavalcanti/orgs',
                               'repos_url': 'https://api.github.com/users/alvarocavalcanti/repos',
                               'events_url': 'https://api.github.com/users/alvarocavalcanti/events{/privacy}',
                               'received_events_url': 'https://api.github.com/users/alvarocavalcanti/received_events',
                               'type': 'User', 'site_admin': False}}
        """
